version: '3.8'

services:
  laravel:
    build: .
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
    environment:
        - WWWUSER=1000
        - WWWGROUP=1000
        - APP_ENV=local
        - APP_DEBUG=true
    networks:
      - shared_network
networks:
  shared_network:
    external: true
    name: shared_network
