version: '3.8'

services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    environment:
      - SE_VNC_NO_PASSWORD=1
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2gb
  laravel:
    build: .
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - selenium-chrome
    environment:
        - WWWUSER=1000
        - WWWGROUP=1000
networks:
  shared_network:
    external: true
    name: shared_network
